check for systemd-creds before proceeding with keepassxc-unlock-setup

diff --git a/keepassxc-unlock-setup b/keepassxc-unlock-setup
--- a/keepassxc-unlock-setup
+++ b/keepassxc-unlock-setup
@@ -39,6 +39,11 @@ if [ ! -f "$kdbx_file" ]; then
   exit 1
 fi
 
+if ! type -p systemd-creds >/dev/null; then
+  echo "systemd-creds absent, cannot proceed; minimum version of systemd required is 250"
+  exit 1
+fi
+
 key_type="host+tpm2"
 echo Checking TPM2 support
 if ! systemd-creds has-tpm2; then
